{% set name = "nbpreview" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nbpreview-{{ version }}.tar.gz
  sha256: 6144f2c0315fff6f83e7ba526949d372080ac77853cc24c985149a04ef5e59aa

build:
  entry_points:
    - nbp = nbpreview.__main__:app
    - nbpreview = nbpreview.__main__:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8,<4.0
  run:
    - click-help-colors >=0.9.1
    - html2text >=2020.1.16
    - httpx >=0.19,<0.24
    - ipython >=7.27,<9.0
    - jinja2 >=3.0.1
    - lxml >=4.6.3
    - markdown-it-py >=1.1,<3.0
    - mdit-py-plugins >=0.3.0
    - nbformat >=5.2.0,<6.0.0
    - picharsso >=2.0.1
    - pillow >=8.3.1,<10.0.0
    - pygments >=2.10.0
    - pylatexenc >=2.10
    - python >=3.8,<4.0
    - rich >=12.4.1
    - term-image >=0.3.0
    - typer >=0.4.1,<0.6.0
    - types-click >=7.1.5
    - validators >=0.18.2,<0.21.0
    - yarl >=1.6.3

test:
  imports:
    - nbpreview
  commands:
    - pip check
    - nbp --help
    - nbpreview --help
  requires:
    - pip

about:
  home: https://github.com/paw-lu/nbpreview
  doc_url: https://nbpreview.readthedocs.io/
  summary: A terminal viewer for Jupyter notebooks. It's like cat for ipynb files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
