{% set name = "nbpreview" %}
{% set version = "0.10.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nbpreview-{{ version }}.tar.gz
  sha256: 6144f2c0315fff6f83e7ba526949d372080ac77853cc24c985149a04ef5e59aa

build:
  entry_points:
    - nbp = nbpreview.__main__:app
    - nbpreview = nbpreview.__main__:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - jinja2 >=3.0.1
    - pillow >=8.3.1,<11.0.0
    - pygments >=2.19.2
    - click-help-colors >=0.9.4
    - html2text >=2025.4.15
    - httpx >=0.28.1,<0.29.0
    - ipython >=9.6.0,<10.0.0
    - lxml >=6.0.2
    - markdown-it-py >=3.0,<4.0
    - mdit-py-plugins >=0.5.0
    - nbformat >=5.10.4
    - picharsso >=2.0.1
    - pylatexenc >=2.10
    - rich >=14.2.0
    - term-image >=0.7.2,<0.8
    - typer >=0.19.2,<0.20.0
    - types-click >=7.1.8
    - validators >=0.35.0,<0.36.0
    - yarl >=1.22.0

test:
  imports:
    - nbpreview
  commands:
    - pip check
    - nbp --help
    - nbpreview --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/paw-lu/nbpreview
  doc_url: https://nbpreview.readthedocs.io/
  summary: A terminal viewer for Jupyter notebooks. It's like cat for ipynb files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
